[project]
name = "project-tmp-rep"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
dependencies = ["lib-tmp-rep @ git+https://github.com/BreadPetya/lib-tmp-rep.git"]

[build-system]
requires = ["uv>=0.1.0"]
build-backend = "uv.build"
